# Generated by Django 3.2.8 on 2021-11-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='profile',
            name='wokrplace',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
